# Generated by Django 4.2.13 on 2024-07-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
