# Generated by Django 4.2.13 on 2024-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
