# Generated by Django 4.2.13 on 2024-07-09 13:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.IntegerField(choices=[(0, 'Incorrect'), (1, 'Correct')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Medium')], default=1),
        ),
    ]
