# Generated by Django 4.2.13 on 2024-07-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_options_question_question_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answer_option'], 'verbose_name_plural': 'Answers'},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_option',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question_id', 'answer_option')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_num',
        ),
    ]
