# Generated by Django 4.2.13 on 2024-07-16 09:22

from django.db import migrations, models
from django.utils.text import slugify

def slugify_quiz_titles(apps, schema_editor):
    Quiz = apps.get_model('quiz', 'Quiz')
    for quiz in Quiz.objects.all():
        quiz.slug = slugify(quiz.title)
        quiz.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_answer_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, null=True),
        ),
        migrations.RunPython(slugify_quiz_titles),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
