# Generated by Django 4.2.13 on 2024-07-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quiznote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizNote',
        ),
    ]
