# Generated by Django 4.2.13 on 2024-07-23 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_alter_answer_answer_option'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuizScore',
            new_name='UserQuizSubmission',
        ),
    ]
