# Generated by Django 4.2.13 on 2024-07-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_userquizsubmission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiznote',
            options={'ordering': ['-created_at']},
        ),
    ]
