# Generated by Django 4.2.13 on 2024-07-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_quiznote_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizNote',
        ),
    ]
