# Generated by Django 4.2.13 on 2024-07-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_quiznote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiznote',
            name='quiz',
        ),
    ]
